### ISSUE TITLE
Can we mandate Black for styling Python code?

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-developer-handbook#88]
https://github.com/kids-first/kf-developer-handbook/blob/f05329b0cc33af1f143588631c432835300f8a7b/docs/guides/python.rst#code-standards says "Use pep-8 for styling code" but every different autoformatter will do that differently. It would simplify and clarify things if we designated a specific formatting tool like https://github.com/psf/black

**Comment by dankolbman** [comment]
I'm ok with specifically mandating black as the for matter of choice, but perhaps hesitant for it to be a hard requirement for legacy reasons.
Will take a stab at rephrasing.
